### ISSUE TITLE
Webseite über Automobiler Verkauf

### ISSUE THREAD

**Issue by YunusEmreDag** [oliver-jung/lva-web-technologien-2024#1]

**Comment by oliver-jung** [comment]
Hier ein kurzes Feedback zur Beschreibung (auch wenn mitterweile nicht mehr vorhanden). Ich gehe im heutigen LB gerne nochmal auf den Upload und die Issue-Verwaltung ein.

Grundsätzlich sollte die Idee vom Umfang her mehr als ausreichend sein und bietet die Flexibilität je nach Fortschritt einzelne Funktionalitäten auszulassen.
Die Komplexität ist je nach Herangehensweise einzustufen. Sofern mit statischen Daten gearbeitet wird, sehe ich keine Probleme.
Wenn NutzerInnen Inhalte einpflegen sollen, braucht es ein Content Management System (inkl. Datenbank und Nutzermanagement) - hier bewegen wir uns eher auf der komplexen Seite. Ich kann jedoch Alternativen aufzeigen wie dies für Demonstrationszwecke vereinfacht werden kann.
Als Mittelweg könnte eine passende API angebunden werden. Eventuell wirst du hier fündig: https://github.com/public-api-lists/public-api-lists?tab=readme-ov-file#vehicle 

Das Mockups ist soweit in Ordnung. Jedoch würde ich die erweiterte Suche auf Grund der Komplexität von Filtern auf eine separate Seite auslagern anstatt sie in der Navigation zu zeigen
