### ISSUE TITLE
Website über Film/Seriensuche 

### ISSUE THREAD

**Issue by BarisicIgor** [oliver-jung/lva-web-technologien-2024#2]
[Projekt.docx](https://github.com/user-attachments/files/17095566/Projekt.docx)

**Comment by oliver-jung** [comment]
Das Projekt sollte vom Umfang her in einem Semester gut bearbeitbar sein und hat ausreichend Komplexität und Flexibilität.

Es gibt zwei wichtige Fragen:
- Woher kommen die Daten zu den Filmen und Serien? (Nutzereingabe, zentral verwaltet, API, Web Scraper)
- Wie werden die personalisierten Daten (persönliche Listen) persistiert (Datenbank mit Nutzermanagement - hohe Komplexität, Möglichkeit zum Speichern und Laden in separatem File - mittlere Komplexität, Speichern im Browsercache - niedrige Komplexität)

Darüber hinaus solltest du dich nach passenden APIs umsehen, die dir Teile der Umsetzung erleichtern / abnehmen können, z.B. https://developer.themoviedb.org/docs/getting-started
