### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Rufceo** [oliver-jung/lva-web-technologien-2024#3]

**Comment by oliver-jung** [comment]
Hallo Paul,

ein durchaus beeindruckender Stand!

Hier ein paar Anmerkungen:
- Die JS Script Teile bitte in eine separate Datei auslagern
- Die Navigation braucht dringend ein RWD, da sie recht lang ist. Idealerweise mittels Hamburger-Menü wie in der LV erklärt
- Die Sprachauswahl würde ich nach rechts stellen und eher mit Länder-Flaggen oder 2-Buchstaben Codes wählen, um Platz zu sparen (du kannst die navigator.language als Basis zum ersten Abgleich verwenden. Das vermeidet manuelle Anpassungen. Siehe https://www.slingacademy.com/article/javascript-get-the-users-preferred-language/)
- Das Kontakt-Formular ist noch etwas unschön. Ich würde pro Eingabe eine Zeile verwenden und etwas mehr Platz andenken. Außerdem fehlt noch die Funktionalität (mehr dazu am 27.11)
- Den Login würde ich in den Footer packen und kleiner gestalten, da er nur für Admins gedacht ist
- Mir fehlt noch ein Impressum (idealerweise ebenfalls im Footer)

Nächste Schritte:
- Unterseiten mit Inhalten befüllen (insbesondere Bilder auf einer separaten Seiten oder in "Über uns")
- Die Reservierung sollte direkt über die Seite eingebunden werden. Im einfachsten Fall wird nach Ausfüllen eines Formulars (Tag, Uhrzeit, Anzahl Personen) eine automatische Mail generiert auf die manuell geantwortet wird (mehr dazu am 27.11). Sofern Bezahl-Services eine Option sind, ist OpenTable (https://www.opentable.de/restaurant-solutions/) wohl der bekannteste Anbieter. Eine kostenloste Variante findet sich hier - allerdings ohne Erfahrungswert (https://tableagent.com/)
- Die Events könnten dynamisch mit externen Inhalten (Facebook, Insta, RSS, ...) oder ebenfalls über das Admin-Interface bespielt werden

LG
Oliver
